In [335]:
import pandas as pd
import numpy as ny

In [336]:
data_df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

In [337]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [338]:
data_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [339]:
clean_df = data_df.copy()

In [340]:
clean_df.columns = [column.lower().replace(" ","_") for column in clean_df.columns]

In [341]:
clean_df = clean_df.rename(columns={"st":"state"})

In [342]:
clean_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [343]:
clean_df["gender"].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [344]:
standardized = {"F":"F",
                "M":"M",
                "Femal":"F",
                "Male":"M",
                "female":"F"}

In [345]:
clean_df["gender"] = clean_df["gender"].replace(standardized)

In [346]:
clean_df["gender"] = clean_df["gender"].fillna("Unknown")

In [347]:
clean_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [348]:
clean_df["state"] = clean_df["state"].str.strip()

In [349]:
state_name = {
    "AZ": "Arizona",
    "Cali": "California",
    "WA": "Washington",
    "NV": "Nevada"
}

In [350]:
clean_df["state"] = clean_df["state"].replace(state_name)

In [351]:
clean_df["state"] = clean_df["state"].fillna("Unknown")

In [352]:
clean_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon',
       'Unknown'], dtype=object)

In [353]:
clean_df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Unknown,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [354]:
clean_df["education"].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

In [355]:
clean_df["education"] = clean_df["education"].replace("Bachelors","Bachelor")

In [356]:
clean_df["customer_lifetime_value"].unique()

array([nan, '697953.59%', '1288743.17%', ..., '2031499.76%', '323912.47%',
       '899704.02%'], shape=(1028,), dtype=object)

In [357]:
clean_df["customer_lifetime_value"] = clean_df["customer_lifetime_value"].str.replace("%","")

In [358]:
clean_df["customer_lifetime_value"].unique()

array([nan, '697953.59', '1288743.17', ..., '2031499.76', '323912.47',
       '899704.02'], shape=(1028,), dtype=object)

In [359]:
clean_df["vehicle_class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car', nan], dtype=object)

In [360]:
luxury = {"Luxury SUV":"Luxury",
          "Sports Car":"Luxury",
          "Luxury Car":"Luxury"}

In [361]:
clean_df["vehicle_class"] = clean_df["vehicle_class"].replace(luxury)

In [362]:
clean_df["vehicle_class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

In [363]:
clean_df["customer_lifetime_value"] = clean_df["customer_lifetime_value"].astype(float)
clean_df["customer_lifetime_value"].unique()

array([       nan,  697953.59, 1288743.17, ..., 2031499.76,  323912.47,
        899704.02], shape=(1028,))

In [364]:
clean_df["number_of_open_complaints"].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

In [365]:
clean_df["number_of_open_complaints"] = clean_df["number_of_open_complaints"].fillna("0/0/0")
clean_df["number_of_open_complaints"].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00',
       '0/0/0'], dtype=object)

In [366]:
clean_df["number_of_open_complaints"] = clean_df["number_of_open_complaints"].astype(str)

In [367]:
split_data = clean_df["number_of_open_complaints"].str.split("/")

In [368]:
clean_df["number_of_open_complaints"] = split_data.str[1]

In [369]:
clean_df["number_of_open_complaints"] = pd.to_numeric(clean_df["number_of_open_complaints"], errors='coerce')

In [370]:
clean_df["number_of_open_complaints"].unique()

array([0, 2, 1, 3, 5, 4])

In [373]:
null_counts = clean_df.isnull().sum()
print(null_counts[null_counts > 0])

customer                   2937
education                  2937
customer_lifetime_value    2940
income                     2937
monthly_premium_auto       2937
policy_type                2937
vehicle_class              2937
total_claim_amount         2937
dtype: int64

In [375]:

clean_df["customer_lifetime_value"] = clean_df["customer_lifetime_value"].fillna(0)
clean_df["income"] = clean_df["income"].fillna(0)
clean_df["monthly_premium_auto"] = clean_df["monthly_premium_auto"].fillna(0)
clean_df["total_claim_amount"] = clean_df["total_claim_amount"].fillna(0)


clean_df["customer"] = clean_df["customer"].fillna("Unknown")
clean_df["education"] = clean_df["education"].fillna("Unknown")
clean_df["policy_type"] = clean_df["policy_type"].fillna("Unknown")
clean_df["vehicle_class"] = clean_df["vehicle_class"].fillna("Unknown")


clean_df.isnull().sum()

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [376]:

clean_df["customer_lifetime_value"] = clean_df["customer_lifetime_value"].astype(int)
clean_df["income"] = clean_df["income"].astype(int)
clean_df["monthly_premium_auto"] = clean_df["monthly_premium_auto"].astype(int)
clean_df["total_claim_amount"] = clean_df["total_claim_amount"].astype(int)

clean_df["number_of_open_complaints"] = clean_df["number_of_open_complaints"].astype(int)


clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   4008 non-null   object
 1   state                      4008 non-null   object
 2   gender                     4008 non-null   object
 3   education                  4008 non-null   object
 4   customer_lifetime_value    4008 non-null   int64
 5   income                     4008 non-null   int64
 6   monthly_premium_auto       4008 non-null   int64
 7   number_of_open_complaints  4008 non-null   int64
 8   policy_type                4008 non-null   object
 9   vehicle_class              4008 non-null   object
 10  total_claim_amount         4008 non-null   int64
dtypes: int64(5), object(6)
memory usage: 344.6+ KB

In [377]:
clean_df.duplicated().sum()

np.int64(2936)

In [378]:
clean_df = clean_df.drop_duplicates(keep="first")


clean_df = clean_df.reset_index(drop=True)


print(clean_df.duplicated().sum())

0

In [379]:
clean_df.to_csv("clean_data.csv", index=False)